fake-authentication:
  fake-tokens:
    # ADMINISTRATOR
    qxQGQdXonygfPdlXwOBFfEToCxLQXD0S:
      Uid: 6ABA9AD15BE8E8CD
      email: user1@mail.com
      name: user1
    # MENTOR
    TW1N4bM7fRpiFLPxaYK6aRvYQohfXy27:
      Uid: B8DEEA4FEE42AD9D
      email: user2@mail.com
      name: user2
    # STAFF
    HFRE4bM7eR4HfGe4aPoI8RvYQohfTffR:
      Uid: DDEEEA4E4432BF6E
      email: user3@mail.com
      name: user3
    # TECKER
    sT5IqVRT0BENw6eFQ0pyjo4t7rwpMzLa:
      Uid: 26C4158B71C6CBE9
      email: user4@mail.com
      name: user4
    # TECKER
    qnZpC7Y1P5liJgJ1PwX9axDLGdSgBUgB:
      Uid: 2B4A8E9FFF232BED
      email: user5@mail.com
      name: user5
    # TECKER
    zB28n6s5LCapemdkSGTB0zdoSgdLfHeV:
      Uid: 34D8BB35832DFEF3
      email: user6@mail.com
      name: user6
    #PARENT (of user4 and user5)
    VREelZomZVgwwXXSbzbNDhxzl0P6UlgP:
      Uid: E596D39ACE5A238C
      email: user7@mail.com
      name: user7
    #PARENT (of user6)
    CUtvy6kwNMWm0T4HxK9GlTtlnCUQ0nnQ:
      Uid: P6Y7T1W9PTV31KWQ
      email: user8@mail.com
      name: user8
    #STAFF
    ydvhRB9iUbYvka6pT1CQDkMcCVyHaPFR:
      Uid: L1J3ZHTVEQYE0UQD
      email: user9@mail.com
      name: user9
    #MENTOR (of user5 and user6)
    Zkgi7GSQNiIwPa5kKanRNl5Vtb1OXkNC:
      Uid: 7Z85FHB9JFY3A20H
      email: user10@mail.com
      name: user10
