server:
  port: ${PORT:8080}

spring:
  mvc:
    locale: es_GT
    converters:
      preferred-json-mapper: gson
  datasource:
    #jdbc:postgresql://localhost:5432/name_db
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 2
      max-idle: 1
      min-idle: 1
      initial-size: 1
      test-while-idle: true
      min-evictable-idle-time-millis: 10000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

authentication:
  firebase:
    databaseUrl: ${FIREBASE_DATABASE_URL:}
    configObject: ${FIREBASE_CONFIG:}
  jwt:
    privateKey: ${JWT_PRIVATE_KEY:}
    publicKey: ${JWT_PUBLIC_KEY:}


